In [2]:
import pandas as pd

print("Imported")

Imported

In [3]:
dict_df = {
    "id"          : [1        ,2         ,3         ,4],
    "name"        : ["ariel"  ,"nadav"   ,"meir"    ,"noam"],
    "age"         : [25       , 24       ,26        ,23],
    "healthy"     : [True     ,True      ,False     ,False],
    "saving_count": [1200     ,1500      ,2140      ,1523],
    "country"     : ["israel" ,"israel"  ,"yarden"  ,"thailand"]
}
df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys()))

display(df)

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

In [4]:
new_df = df.sort_values(by=['name','saving_count'], ascending=[False, True],inplace=False,
                        na_position='last',kind="quicksort",ignore_index=True)

### (by="mpg",ascending=True,inplace=False,na_position="last",kind="quicksort",ignore_index=False,key=None)

# Order rows by values of a column (low to high).
## by -> if list of columns it is gonna sort the df by the first element if there is equal
# elements in 2 different indexes it will sort by the next element of by=.
## ascending = False -> from lower to higher. ascending = False -> from higher to lower.
## inplace = False -> Default, send a new sorted *copy* , ...=True -> change the original object(return None).
## na_position='last' -> determine where the NaN Values will be sorted to(last/first).
## kind="quicksort" -> determine the sort method,(mergesort->more stable,heapsort->less common)
## ignore_index=True -> reset the indexes .
## key -> lambda function. lambda input -> Series('name') before the sort.

display(new_df)

   id   name  age  healthy  saving_count   country
0   4   noam   23    False          1523  thailand
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   1  ariel   25     True          1200    israel

In [5]:
new_df = df.rename(columns = {'name':'eman'},
                   index={0: 'zero', 1: 'one'},
                   inplace=False,
                   errors='ignore',)
# Rename the columns of a DataFrame only changing the metadata.
## errors='ignore' -> Default ignore the error if not key found.(raise is the negate for ignore)

display(new_df)

      id   eman  age  healthy  saving_count   country
zero   1  ariel   25     True          1200    israel
one    2  nadav   24     True          1500    israel
2      3   meir   26    False          2140    yarden
3      4   noam   23    False          1523  thailand

In [24]:
df2 = pd.DataFrame(dict_df,index=[5,1,4,7])
display(df2)
new_df1 = df2.sort_index()
new_df2 = df2.sort_index(ignore_index=True)

# Sort the index of a DataFrame
### (axis=0,ascending=True,inplace=False,kind='quicksort'
### ,na_position='last',sort_remaining=True,ignore_index=False,key=None)
## axis = 0 -> Default, sort by index of rows. axis = 1 -> sort by column name.
## ignore_index = True -> reset the index
display(new_df1)
display(new_df2)

   id   name  age  healthy  saving_count   country
5   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
4   3   meir   26    False          2140    yarden
7   4   noam   23    False          1523  thailand

   id   name  age  healthy  saving_count   country
1   2  nadav   24     True          1500    israel
4   3   meir   26    False          2140    yarden
5   1  ariel   25     True          1200    israel
7   4   noam   23    False          1523  thailand

   id   name  age  healthy  saving_count   country
0   2  nadav   24     True          1500    israel
1   3   meir   26    False          2140    yarden
2   1  ariel   25     True          1200    israel
3   4   noam   23    False          1523  thailand

In [34]:
df.sort_values(by='id',inplace=True)
display(df)
new_df = df.reset_index()
# the existing index transfer into column in df like id/name
# and new indexing added.(0,1,2)
### (level=None,drop=False,inplace=False)
## level -> for multi index let you choose what level to reset
## drop=False -> Default, saving the index as column, ...=True-> drop the existing index.

display(new_df)

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

   index  id   name  age  healthy  saving_count   country
0      0   1  ariel   25     True          1200    israel
1      1   2  nadav   24     True          1500    israel
2      2   3   meir   26    False          2140    yarden
3      3   4   noam   23    False          1523  thailand

In [45]:
display(df)
new_df = df.drop(axis=1,columns=['id','name'],index=[0,1])
# Drop columns from DataFrame
### (labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
## labels -> when you insert value you have to check the axis parameter they need to set integrated.
## axis -> '0' for rows, '1' for columns.
## index -> ignore the axis it will remove by indexes you mention.
## columns -> ignore the axis it will remove by columns.

display(new_df)

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

   age  healthy  saving_count   country
2   26    False          2140    yarden
3   23    False          1523  thailand

In [87]:
df = pd.DataFrame(dict_df)
display(df)
melt_df = pd.melt(df,id_vars=['id','name'],value_vars=['saving_count','healthy','country','age'],var_name='column',
                 value_name='column_value',ignore_index=False)
#Gather columns into rows.
# if you mention both id_vars and value_var it will drop the columns that have not mentioned.
## problem with time complexity, when you not have between 100k-500k rows and only tens of columns
display(melt_df)

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

   id   name        column column_value
0   1  ariel  saving_count         1200
1   2  nadav  saving_count         1500
2   3   meir  saving_count         2140
3   4   noam  saving_count         1523
0   1  ariel       healthy         True
1   2  nadav       healthy         True
2   3   meir       healthy        False
3   4   noam       healthy        False
0   1  ariel       country       israel
1   2  nadav       country       israel
2   3   meir       country       yarden
3   4   noam       country     thailand
0   1  ariel           age           25
1   2  nadav           age           24
2   3   meir           age           26
3   4   noam           age           23

In [88]:
pivot_df = melt_df.pivot(index=['name'],columns=['column'],values='column_value').reset_index()
#Spread rows into columns
### (index=None, columns=None, values=None)
## index cannot contain duplicate values.

display(pivot_df)

column   name age   country healthy saving_count
0       ariel  25    israel    True         1200
1        meir  26    yarden   False         2140
2       nadav  24    israel    True         1500
3        noam  23  thailand   False         1523

In [122]:
df1 = df[['name','saving_count']]
df2 = df[['name','saving_count']].sort_index(ascending=False)

display(df1)
display(df2)

df3 = pd.concat([df1,df2], axis=0,join='outer',ignore_index=True)

#Append by indexes mostly
# axis = 0 -> concat with same columns(label) |
# axis = 1 -> concat with same indexes  --
# join = 'outer' -> Default, saving existing indexes and fill NaN where index value is missed.
# join = 'inner' -> saving only integrated indexes.
# verify_integrity=True -> raise an error if there is duplicate indexes.
display(df3)

    name  saving_count
0  ariel          1200
1  nadav          1500
2   meir          2140
3   noam          1523

    name  saving_count
3   noam          1523
2   meir          2140
1  nadav          1500
0  ariel          1200

    name  saving_count
0  ariel          1200
1  nadav          1500
2   meir          2140
3   noam          1523
4   noam          1523
5   meir          2140
6  nadav          1500
7  ariel          1200

In [ ]:
dict_df = {
    "id"          : [1        ,2         ,3              ,4            ,5        ,106       ],
    "name"        : ["ariel"  ,"nadav"   ,"maor"         ,"noam"       ,"lior"   ,"hamarmir"],
    "age"         : [25       , 24       ,26             ,26           ,None     ,45        ],
    "healthy"     : [True     ,True      ,False          ,False        ,True     ,True      ],
    "saving_count": [1200     ,1500      ,2140           ,1523         ,3000     ,2500      ],
    "addicted"    : ["high"   ,"medium"  ,"high"         ,"medium"     ,"less"   ,"not"],
    "country"     : ["israel" ,"israel"  ,'north_korea'  ,"thailand"   ,'peru'   ,'greece'  ]
}

df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys()))

df1 = df.iloc[:,[0,1,2,3]]
df2 = df.iloc[:4,[0,4,5,6]]
display(df1,df2)
merged_df = pd.merge(
    left=df1,
    right=df2,
    on=['id'],
    how="outer",
    indicator=True,
    validate="one_to_one"
)
### (left,right,how="inner",on=None,left_on=None,right_on=None,left_index=False,right_index=False,sort=False,suffixes=("_x", "_y"),
###    copy=None,indicator=False,validate=None)
## how = 'inner' -> keys that exists in both tables
## how = 'left'  -> keys that exists in left table.
## how = 'right' -> keys that exists in right table.
## how = 'outer' -> all keys from both tables(missing values in one table will be filled with NaN)
## how = 'cross' -> each row from left table will be served with all rows from the right table.(remove 'on' hp)
## on  -> you can choose the columns that exists in both tables, the merged will be considered by their priority order.
## left_on=None,right_on=None -> here you can mention specific column to compare with the other table.(in case of unrelated names)
## left_index=False,right_index=False -> use the right/left table index as his 'on' column.
## sort=False -> sort by keys or not sorted(Default)
## suffixes=("_x", "_y") -> if there is same column names but not in 'on', it will rename 'score'_x for left 'score'_y for right.
## suffixes=(None, "_y") -> will rename only the right table.
## indicator=True -> will return one more column: '_merge', this column use is to explain in what table the row exists.(you can name it)
## validate="one_to_one"  -> will allow to the same key to return only 1 row else ERROR.
## validate="one_to_many" -> will allow to the same key to return more than 1 row only for right table.
## validate="many_to_one" -> will allow only for left table to return more than 1 row only for left table.
## validate="many_to_many"-> will allow  for both tables to return more than 1 row.

display(merged_df)