In [1]:
import pandas as pd
print("Imported!")

Imported!

In [2]:
dict_df = {
    "id"          : [1        ,2         ,3         ,4],
    "name"        : ["ariel"  ,"nadav"   ,"meir"    ,"noam"],
    "age"         : [25       , 24       ,26        ,23],
    "healthy"     : [True     ,True      ,False     ,False],
    "saving_count": [1200     ,1500      ,2140      ,1523],
    "country"     : ["israel" ,"israel"  ,"yarden"  ,"thailand"]
}
df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys()))

display(df)

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

In [4]:
print("DataFrame:")
display(df)
selected = df.iloc[1:3]
#Select rows df[1],df[2] max edge excluded .
print("df.iloc[1:3]")
display(selected)

DataFrame:

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.iloc[1:3]

   id   name  age  healthy  saving_count country
1   2  nadav   24     True          1500  israel
2   3   meir   26    False          2140  yarden

In [5]:
print("DataFrame:")
display(df)
selected = df.iloc[:, [1, 2, 5]]
#Select [:,](all rows) columns in positions 1, 2 and 5 (first column is 0).
print("df.iloc[:, [1, 2, 5]]")
display(selected)

DataFrame:

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.iloc[:, [1, 2, 5]]

    name  age   country
0  ariel   25    israel
1  nadav   24    israel
2   meir   26    yarden
3   noam   23  thailand

In [6]:
print("DataFrame:")
display(df)
selected = df.loc[0:2,'name':'healthy']
#Select rows 0,1,2(both edges included) all columns between name and healthy .
print("df.loc[1:2,'name':'healthy']")
display(selected)

DataFrame:

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.loc[1:2,'name':'healthy']

    name  age  healthy
0  ariel   25     True
1  nadav   24     True
2   meir   26    False

In [7]:
print("DataFrame:")
display(df)
selected = df.loc[df["age"] > 24, ["name", "age"]]
#Select rows meeting logical condition, and only
#the specific columns .
print('df.loc[df["age"] > 24, ["name", "age"]]')
display(selected)

DataFrame:

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.loc[df["age"] > 24, ["name", "age"]]

    name  age
0  ariel   25
2   meir   26

In [8]:
print("DataFrame:")
display(df)
selected_iat = df.iat[1, 2]
selected_iloc = df.iloc[1,2]
# Access single value by index
# Working by [row_position,field_position]. not column or index
# iat meant to be used for specific field in the matrix while iloc normally used to locate rows,

print("\ndf.iat[1, 2]")
display(selected_iat)
print("\ndf.iloc[1, 2]")
display(selected_iloc)

DataFrame:

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.iat[1, 2]

np.int64(24)

df.iloc[1, 2]

np.int64(24)

In [9]:
print("DataFrame:")
display(df)
selected = df.at[3, 'age']
# Access single value by label
print("df.at[3, 'age']")
display(selected)

DataFrame:

   id   name  age  healthy  saving_count   country
0   1  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   3   meir   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.at[3, 'age']

np.int64(23)