In [1]:
import pandas as pd
print("Imported")

Imported

In [14]:
dict_df = {
    "id"          : [2        ,2         ,2         ,4],
    "name"        : ["ariel"  ,"nadav"   ,"ariel"    ,"noam"],
    "age"         : [25       , 24       ,26        ,23],
    "healthy"     : [True     ,True      ,False     ,False],
    "saving_count": [1200     ,1500      ,2140      ,1523],
    "country"     : ["israel" ,"israel"  ,"yarden"  ,"thailand"]
}
df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys()))

display(df)

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

In [16]:
print("DataFrame")
display(df)

after_drop = df.drop_duplicates(subset=["name","id"],keep=False,inplace=False,ignore_index=True)
#Remove duplicate rows (only considers columns).
### (subset=None,*,keep="first",inplace=False,ignore_index=False)
## subset=["name"] -> focusing the drop to be applied on rows with duplicate specific columns.(all(subset))
## keep = ["first","last",False] ->
# "first" -> first in order stay.
# "last" -> last in order stay.
# False -> drop all duplicate rows. nothing stay
## inplace -> return None, and changing the original dataframe.(Default=False)
## ignore_index=True -> reindexing the dateframe again from 0.
print("df.drop_duplicates()")
display(after_drop)

DataFrame

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.drop_duplicates()

   id   name  age  healthy  saving_count   country
0   2  nadav   24     True          1500    israel
1   4   noam   23    False          1523  thailand

In [25]:
print("DateFrame")
display(df)
selected = df.sample(n= len(df),replace=True,random_state=42)
#Randomly select fraction of rows.
###(n=None,frac=None,replace=False,weights=None,random_state=None,axis=None,ignore_index=False)
## frac=0.5 -> 50% of the dataframe rows will be selected to return.(WARNING: n and frac hyperparameters can't be used together)
## n=2 -> 2 random samples to return.(WARNING: n and frac hyperparameters can't be used together)
## replace=False -> Default, can't choose the same row more than 1 time. ...=True the same row might choose more than 1 time.


print("df.sample(frac=0.5)")
display(selected)

DateFrame

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.sample(frac=0.5)

   id   name  age  healthy  saving_count   country
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand
0   2  ariel   25     True          1200    israel
2   2  ariel   26    False          2140    yarden

In [29]:
print("Dataframe")
display(df)
selected = df.nlargest(n = 2, columns=['id'],keep="all")
#Select and order top n entries.
### (n,columns,keep='first')
## keep="all" -> in case there is tie and the number of selected rows is higher than
# the *n* hyperparameter so the number of selected rows will be all values with max values.

print("df.nlargest(n, 'value')")
display(selected)

Dataframe

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.nlargest(n, 'value')

   id   name  age  healthy  saving_count   country
3   4   noam   23    False          1523  thailand
0   2  ariel   25     True          1200    israel

In [32]:
print("Dataframe")
display(df)
selected = df.nsmallest(n = 2, columns=['id'],keep='last')
#Select and order bottom n entries.
### (n,columns,keep='first')
## keep="all" -> in case there is tie and the number of selected rows is higher than
# the *n* hyperparameter so the number of selected rows will be all values with max values.

print("df.nsmallest(n = 2, columns=['id'],keep='last')")
display(selected)

Dataframe

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.nsmallest(n = 2, columns=['id'],keep='all')

   id   name  age  healthy  saving_count country
2   2  ariel   26    False          2140  yarden
1   2  nadav   24     True          1500  israel

In [33]:
print("Dataframe")
display(df)

selected = df.head(n=-2)
#Select first n rows.
## n = 5 -> Default, will return the first 5 rows.
## n = -2 -> will return all rows except the last 2 rows.

print("df.head(-2)")
display(selected)

Dataframe

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.head(-2)

   id   name  age  healthy  saving_count country
0   2  ariel   25     True          1200  israel
1   2  nadav   24     True          1500  israel

In [37]:
print("Dataframe")
display(df)

selected = df.tail(n=-2)
#Select first n rows.
## n = 5 -> Default, wil return 5 last rows
## n = -2 -> will return all rows except the first 2 rows.

print("df.tail(-2)")
display(selected)

Dataframe

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.tail(-2)

   id   name  age  healthy  saving_count   country
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

In [42]:
print("Dataframe")
display(df)

selected1 = df[df["healthy"] == True]
selected2 = df[
                (df["healthy"] == False) &
                (df["name"]== "ariel") |
                (df["age"]== 25)
                ]
selected3 = df[df["age"].between(20, 30)]
selected4 = df[ df["country"].isin( ["israel", "thailand"] ) ]
selected5 = df[ df["name"].str.contains("ri",case=False) ]
## case=False-> it will find the string if its "A" | "a".


display(selected5)

Dataframe

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

   id   name  age  healthy  saving_count country
0   2  ariel   25     True          1200  israel
2   2  ariel   26    False          2140  yarden