In [1]:
import pandas as pd
print("Imported")

Imported

In [20]:
dict_df = {
    "id"          : [2        ,2         ,2         ,4],
    "name"        : ["ariel"  ,"nadav"   ,"ariel"    ,"noam"],
    "age"         : [25       , 24       ,26        ,23],
    "healthy"     : [True     ,True      ,False     ,False],
    "saving_count": [1200     ,1500      ,2140      ,1523],
    "country"     : ["israel" ,"israel"  ,"yarden"  ,"thailand"]
}
df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys())
                  )

display(df)

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

In [45]:
print("DataFrame")
display(df)

regular_expression_1 = r"me$"               # end with "me"
regular_expression_2 = r"e"                 # contain the letter "e"
regular_expression_3 = r"^c"                # start with "c"
regular_expression_4 = r"^h.*y$"            # start with "h", ends with "y"
regular_expression_5 = r"^(?!name$).*"      # every string except "name"
regular_expression_6 = r"^(?=.*a)(?=.*e).*" # every string with "h" and "y" in it

filtered_df = df.filter(axis=1,regex=regular_expression_6)
# Select columns whose name matches regular expression regex.
### (items=None, like=None, regex=None, axis=None)
## items -> name of columns to return
## like="ou"-> return only columns with "ou" in it.(axis="columns"\1)
## like="a"-> return only indexes with "a" in it.(axis="index"\0)


print(f"df.filter(axis=1,regex='{regular_expression_6}')")
display(filtered_df)

DataFrame

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.filter(axis=1,regex='^(?=.*a)(?=.*e).*')

    name  age  healthy
0  ariel   25     True
1  nadav   24     True
2  ariel   26    False
3   noam   23    False

![image.png](attachment:4a887565-c0ab-4c20-b163-a60280c0dcf0.png)

In [55]:
print("DataFrame")
display(df)
age_limit = 25
boolean_expression_1 = '~ healthy > 0 and age > 24'
boolean_expression_2 = 'country in ["israel","thailand"]'
boolean_expression_3 = 'age > @age_limit' 

selected = df.query(expr=boolean_expression_3)
# query() allows Boolean expressions for filtering rows.
### (expr,engine,inplace=False,**kwargs)
## expression -> boolean expression for pandas to select rows. 
## engine -> ["numexpr","python"]
# numexpr -> for numeric boolean query (relevant for big data sets)
# "python" -> Default, as string 

print("df.query('Length > 7')")
display(selected)

DataFrame

   id   name  age  healthy  saving_count   country
0   2  ariel   25     True          1200    israel
1   2  nadav   24     True          1500    israel
2   2  ariel   26    False          2140    yarden
3   4   noam   23    False          1523  thailand

df.query('Length > 7')

   id   name  age  healthy  saving_count country
2   2  ariel   26    False          2140  yarden