In [1]:
import pandas as pd
print("Imported")

Imported

In [2]:
dict_df = {
    "id"          : [1        ,2         ,3              ,4            ,5        ],
    "name"        : ["ariel"  ,"nadav"   ,"maor"         ,"noam"       ,"lior"   ],
    "age"         : [25       , 24       ,26             ,23           ,21       ],
    "healthy"     : [True     ,True      ,False          ,False        ,True     ],
    "saving_count": [1200     ,1500      ,2140           ,1523         ,3000     ],
    "country"     : ["israel" ,"israel"  ,'north_korea'  ,"thailand"   ,'peru'   ]
}
df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys()))

display(df)

   id   name  age  healthy  saving_count      country
0   1  ariel   25     True          1200       israel
1   2  nadav   24     True          1500       israel
2   3   maor   26    False          2140  north_korea
3   4   noam   23    False          1523     thailand
4   5   lior   21     True          3000         peru

In [3]:
print("DataFrame:")
display(df)
vc = df.value_counts(subset=['id','country'],sort=True,dropna=False)
#Count number of rows with each unique value of variable
###(subset=None,normalize=False,sort=True,ascending=False,dropna=True)
## normalize=True -> Default, will convert the count column to precent of all value_count object indexes.
## dropna=True -> Default, indexes with NaN in the subset column will not be included in the counting schema.

print("df['name'].value_counts()")
print(vc)

nan_count_2_id = vc.loc[2,'israel']
print(nan_count_2_id)

DataFrame:

   id   name  age  healthy  saving_count      country
0   1  ariel   25     True          1200       israel
1   2  nadav   24     True          1500       israel
2   3   maor   26    False          2140  north_korea
3   4   noam   23    False          1523     thailand
4   5   lior   21     True          3000         peru

df['name'].value_counts()
id  country
1   israel         1
2   israel         1
3   north_korea    1
4   thailand       1
5   peru           1
Name: count, dtype: int64
1

In [4]:
len(df) # of rows in DataFrame.

5

In [5]:
df.shape #Tuple of rows and columns in DataFrame.

(5, 6)

In [6]:
df_size = df.size
#Size of all cells in df.
print(df_size)

30

In [7]:
df.nunique(axis=1,dropna=False) # count of unique values in a column.

0    5
1    6
2    6
3    6
4    6
dtype: int64

In [8]:
df.describe() # Basic descriptive and statistics for each column (or GroupBy).

             id        age  saving_count
count  5.000000   5.000000      5.000000
mean   3.000000  23.800000   1872.600000
std    1.581139   1.923538    716.933609
min    1.000000  21.000000   1200.000000
25%    2.000000  23.000000   1500.000000
50%    3.000000  24.000000   1523.000000
75%    4.000000  25.000000   2140.000000
max    5.000000  26.000000   3000.000000

In [9]:
numeric_cols = df.select_dtypes(include='number').drop(columns=['id'])
display(numeric_cols)
min_df = numeric_cols.min()
#Minimum value in each object.
print(min_df)

   age  saving_count
0   25          1200
1   24          1500
2   26          2140
3   23          1523
4   21          3000

age               21
saving_count    1200
dtype: int64

In [10]:
display(numeric_cols)

max_df = numeric_cols.max(axis=0)
#Maximum value in each object.
print(max_df)

   age  saving_count
0   25          1200
1   24          1500
2   26          2140
3   23          1523
4   21          3000

age               26
saving_count    3000
dtype: int64

In [11]:
display(numeric_cols)

mean_df = numeric_cols.mean(axis=0)
#Mean value of each object
print(mean_df)

   age  saving_count
0   25          1200
1   24          1500
2   26          2140
3   23          1523
4   21          3000

age               23.8
saving_count    1872.6
dtype: float64

In [12]:
display(numeric_cols)

var_df = numeric_cols.var(axis=0)
#Variance of each object.
print(var_df)


import numpy as np

mean_age = numeric_cols['age'].mean()
after_sub_power = np.power([value-mean_age for value in numeric_cols['age']],2)
print(f'\n\r{after_sub_power}')
sum_after_sub = np.sum(after_sub_power)
print(sum_after_sub)
result_var_age = np.divide(sum_after_sub,(len(numeric_cols['age'])-1))
print("age var:",result_var_age)

   age  saving_count
0   25          1200
1   24          1500
2   26          2140
3   23          1523
4   21          3000

age                  3.7
saving_count    513993.8
dtype: float64

[1.44 0.04 4.84 0.64 7.84]
14.8
age var: 3.7

In [13]:
std_df = numeric_cols['age'].std()
# Standard deviation of each object.
print(std_df)

age_seris = numeric_cols['age']

m = np.mean(age_seris)
st = np.subtract(age_seris, m)
power_st = np.power(st ,2)
m_power_st = np.sum(power_st)/(len(age_seris)-1) # (len(age_seris)-1) not in np.mean()
print("age std: ",np.sqrt(m_power_st))

1.9235384061671346
age std:  1.9235384061671346

In [14]:
sum_numeric = numeric_cols.sum()
# Sum values of each object.
print(sum_numeric)

age              119
saving_count    9363
dtype: int64

In [15]:
count_df = df.count()
# Count non-NA/null values of each object.
print(count_df)

id              5
name            5
age             5
healthy         5
saving_count    5
country         5
dtype: int64

In [16]:
numeric_median = numeric_cols.median()
#Median value of each object.
print(numeric_median)
sorted_numeric = numeric_cols.sort_values(by='age',ascending=True,ignore_index=True)
print(sorted_numeric['age'][(len(sorted_numeric['age']))//2])

age               24.0
saving_count    1523.0
dtype: float64
24

In [17]:
q = numeric_cols.quantile(q=[0.25,0.75])
print('numeric_cols.quantile(q=[0.25,0.75])\n',q)
#Quantiles of each object. starting a values range for each numeric column,then you enter the precent you want to see.
###(q=0.5,axis=0,interpolation='linear',method='single')
## q -> the precents you want to calculate.(0-1)
## interpolation            -> the calculating of the missing value.
## interpolation='linear'   -> Proportional calculation between values.
## interpolation='midpoint' -> mean of both nearest values.
## interpolation='nearest'  -> choosing the nearest value to the calculated precents.
## interpolation='higher'   -> higher value chosen.
## interpolation='lower'    -> lower value chosen.
## method='single'          -> Default. calculating each column separately.
## method='table'           -> calculating the all table with relations between columns(lower,higher,nearest).

Q1 = q.loc[0.25]                ## represent of the value in the 25% of the values range
Q3 = q.loc[0.75]                ## represent of the value in the 75% of the values range
IQR = Q3 - Q1

lower_boundary = Q1-1.5*IQR     ## represent the min edge of the normal value,all lower values in to continue will be outliers.
print(f"\nLower Boundary:\n\r{lower_boundary}")

upper_boundary = Q3+1.5*IQR     ## represent the max edge of the normal value,all higher values will be outliers.
print(f"\nUpper Boundary:\n\r{upper_boundary}")

numeric_cols.quantile(q=[0.25,0.75])
        age  saving_count
0.25  23.0        1500.0
0.75  25.0        2140.0

Lower Boundary:
age              20.0
saving_count    540.0
dtype: float64

Upper Boundary:
age               28.0
saving_count    3100.0
dtype: float64

In [18]:
display(df)
df['age'] = df['age'].apply(lambda x: x + 10)
display(df)
#Apply function to each object.

df['saving_count'] = df['saving_count'].apply(lambda x: max(x,max(df['saving_count'])))
display(df)

df['country'] = df['country'].apply(
    lambda country:  None if country == 'israel' else country)
display(df)

def add_number(series:pd.Series,number:int):
    return series+number

df['id'] = df['id'].apply(add_number,number=20)
display(df)

   id   name  age  healthy  saving_count      country
0   1  ariel   25     True          1200       israel
1   2  nadav   24     True          1500       israel
2   3   maor   26    False          2140  north_korea
3   4   noam   23    False          1523     thailand
4   5   lior   21     True          3000         peru

   id   name  age  healthy  saving_count      country
0   1  ariel   35     True          1200       israel
1   2  nadav   34     True          1500       israel
2   3   maor   36    False          2140  north_korea
3   4   noam   33    False          1523     thailand
4   5   lior   31     True          3000         peru

   id   name  age  healthy  saving_count      country
0   1  ariel   35     True          3000       israel
1   2  nadav   34     True          3000       israel
2   3   maor   36    False          3000  north_korea
3   4   noam   33    False          3000     thailand
4   5   lior   31     True          3000         peru

   id   name  age  healthy  saving_count      country
0   1  ariel   35     True          3000         None
1   2  nadav   34     True          3000         None
2   3   maor   36    False          3000  north_korea
3   4   noam   33    False          3000     thailand
4   5   lior   31     True          3000         peru

   id   name  age  healthy  saving_count      country
0  21  ariel   35     True          3000         None
1  22  nadav   34     True          3000         None
2  23   maor   36    False          3000  north_korea
3  24   noam   33    False          3000     thailand
4  25   lior   31     True          3000         peru