In [56]:
import pandas as pd
import numpy as np
print("Imported")

Imported

In [102]:
dict_df = {
    "id": [1, 2, 3, 4, 5],
    "name": ["ariel", "nadav", "maor", "noam", "lior"],
    "age": [25., None, 26., 23., 21.],
    "healthy": [True, True, False, False, None],
    "saving_count": [1200., 1500., np.nan, None, 3000.],
    "country": ["israel", None, 'peru', None, 'peru']
}
df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys()))

display(df)

   id   name   age healthy  saving_count country
0   1  ariel  25.0    True        1200.0  israel
1   2  nadav   NaN    True        1500.0    None
2   3   maor  26.0   False           NaN    peru
3   4   noam  23.0   False           NaN    None
4   5   lior  21.0    None        3000.0    peru

In [72]:
clean_df = df.dropna(axis=1,subset=[0,1,2],how='any')
# Drop rows with any column having None(python missing)/NaN(number missing)/NaT(time missing) data.
# Default-> removing the row with the missing value.
### (axis=0,how='any',thresh=None,subset=None,inplace=False,ignore_index=False)
## axis = 0 -> rows .axis = 1-> columns.
## how='any' -> if there is one missing value in any column -- drop row (default).
## how='all' -> if there is missing value in all columns -- drop row.
## thresh -> if there is thresh count of existing values in the axis, it will be safe.
## subset -> set the specific columns/rows you desire.

display(clean_df)

   id   name  age  healthy      country
0   1  ariel   25     True       israel
1   2  nadav   24     True       israel
2   3   maor   26    False  north_korea
3   4   noam   23    False     thailand
4   5   lior   21     True         peru

In [107]:
filled_df = df.fillna(value=({
    'age': np.median(df.dropna(axis=0,how='any')['age']),
    'healthy': False,
    'saving_count': np.mean(df['saving_count']),
    'country': df['country'].mode()[0]
}))
# Replace all NA/null data with value.
###( value=None,axis=None,inplace=False,limit=None)
## value -> the values to fill the missing value,(int,str,boll,dict[column])
## limit -> will keep dropping until the limit value over.(limit=2, only 2 values will be filled)

display(filled_df)

display(df['age'],df['age'].ffill())
## fill by the previews value.

print('='*50)
display(df['age'],df['age'].bfill())
## fill by the next value.

C:\Users\User\AppData\Local\Temp\ipykernel_3220\2808623178.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  filled_df = df.fillna(value=({

   id   name   age  healthy  saving_count country
0   1  ariel  25.0     True        1200.0  israel
1   2  nadav  25.0     True        1500.0    peru
2   3   maor  26.0    False        1900.0    peru
3   4   noam  23.0    False        1900.0    peru
4   5   lior  21.0    False        3000.0    peru

0    25.0
1     NaN
2    26.0
3    23.0
4    21.0
Name: age, dtype: float64

0    25.0
1    25.0
2    26.0
3    23.0
4    21.0
Name: age, dtype: float64

==================================================

0    25.0
1     NaN
2    26.0
3    23.0
4    21.0
Name: age, dtype: float64

0    25.0
1    26.0
2    26.0
3    23.0
4    21.0
Name: age, dtype: float64