In [1]:
import pandas as pd
import numpy as np
import time


print("Imported")

Imported

In [2]:
dict_df = {
    "id"          : [1        ,2         ,3              ,4            ,5        ,106         ],
    "name"        : ["ariel"  ,"nadav"   ,"maor"         ,"noam"       ,"lior"   ,"hamarmir"],
    "age"         : [25       , 24       ,26             ,23           ,21       ,45        ],
    "healthy"     : [True     ,True      ,False          ,False        ,True     ,True      ],
    "saving_count": [1200     ,1500      ,2140           ,1523         ,3000     ,2500      ],
    "country"     : ["israel" ,"israel"  ,'north_korea'  ,"thailand"   ,'peru'   ,'greece'  ]
}

df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys()))

display(df)

    id      name  age  healthy  saving_count      country
0    1     ariel   25     True          1200       israel
1    2     nadav   24     True          1500       israel
2    3      maor   26    False          2140  north_korea
3    4      noam   23    False          1523     thailand
4    5      lior   21     True          3000         peru
5  106  hamarmir   45     True          2500       greece

In [3]:
df.assign(**{
          "name_changing" : lambda series: series['name'].where(series['name'] != 'noam' , None),
          "age_in_two_years":df['age']+2,
          "age_in_three_years":lambda series: series['age_in_two_years']+1,
          "column_adding_time":time.strftime("%H:%M:%S---%d/%m/%y"),
          "positive":True
})

# Compute and append one or more new columns.
# with 'lambda' you can mention the column you are building during the assign function.
# if the name of column already exists the new column will replace the column.
# the assign function know to sort when you send series for new column by the series indexes
# it is matching index for index.

,id,name,age,healthy,saving_count,country,name_changing,age_in_two_years,age_in_three_years,column_adding_time,positive
0,1,ariel,25,True,1200,israel,ariel,27,28,18:49:08---22/10/26,True
1,2,nadav,24,True,1500,israel,nadav,26,27,18:49:08---22/10/26,True
2,3,maor,26,False,2140,north_korea,maor,28,29,18:49:08---22/10/26,True
3,4,noam,23,False,1523,thailand,None,25,26,18:49:08---22/10/26,True
4,5,lior,21,True,3000,peru,lior,23,24,18:49:08---22/10/26,True
5,106,hamarmir,45,True,2500,greece,hamarmir,47,48,18:49:08---22/10/26,True

In [4]:
groups , bins = pd.qcut(df['id'], q=3, labels=[33,66,99],retbins=True,precision=2)
print(f"groups: {groups}.\n\rbins: {bins}")
df['new_qcut'] = pd.qcut(df['id'], q=3, labels=[33,66,99],precision=2)
# qcut will disperse the values to q groups never-mind the range.

groups , bins = pd.cut(df['id'], bins=3, labels=[33,66,99],retbins=True,precision=2)
print(f"groups: {groups}.\n\rbins: {bins}")
df['new_cut'] = pd.cut(df['id'], bins=3, labels=[33,66,99],precision=2)
# cut will made value range and cluster the groups by 1/q of the range each.

### pd.qcut(x,q,labels=None,retbins=False,precision=3,duplicates='drop')
## x -> values to cluster
## q -> the desired precents of groups.
## labels=[33,66,99] -> for q=3;  q1 = 33 , q2 = 66 , q3 = 99.
## duplicates='drop' -> when you have duplicates separate boundary it will drop the duplicated boundary.
## duplicates='drop' -> (not changing the df)
## duplicates='drop' -> raise ERROR if duplicate boundary.

display(df)

groups: 0    33
1    33
2    66
3    66
4    99
5    99
Name: id, dtype: category
Categories (3, int64): [33 < 66 < 99].
bins: [  1.           2.66666667   4.33333333 106.        ]
groups: 0    33
1    33
2    33
3    33
4    33
5    99
Name: id, dtype: category
Categories (3, int64): [33 < 66 < 99].
bins: [  0.895  36.     71.    106.   ]

    id      name  age  healthy  saving_count      country new_qcut new_cut
0    1     ariel   25     True          1200       israel       33      33
1    2     nadav   24     True          1500       israel       33      33
2    3      maor   26    False          2140  north_korea       66      33
3    4      noam   23    False          1523     thailand       66      33
4    5      lior   21     True          3000         peru       99      33
5  106  hamarmir   45     True          2500       greece       99      99