In [1]:
import pandas as pd
import numpy as np
print("Imported")

Imported

In [2]:
dict_df = {
    "id"          : [1        ,2         ,3              ,4            ,5        ,106         ],
    "name"        : ["ariel"  ,"nadav"   ,"maor"         ,"noam"       ,"lior"   ,"hamarmir"],
    "age"         : [25       , 24       ,26             ,26           ,None       ,45        ],
    "healthy"     : [True     ,True      ,False          ,False        ,True     ,True      ],
    "saving_count": [1200     ,1500      ,2140           ,1523         ,3000     ,2500      ],
    "country"     : ["israel" ,"israel"  ,'north_korea'  ,"thailand"   ,'peru'   ,'greece'  ]
}

df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys()))

display(df)

    id      name   age  healthy  saving_count      country
0    1     ariel  25.0     True          1200       israel
1    2     nadav  24.0     True          1500       israel
2    3      maor  26.0    False          2140  north_korea
3    4      noam  26.0    False          1523     thailand
4    5      lior   NaN     True          3000         peru
5  106  hamarmir  45.0     True          2500       greece

In [3]:
df_dates = pd.DataFrame(
    {'sales': [100, 150, 200]},
    index=pd.to_datetime([
        '2026-01-01',
        '2026-01-02',
        '2026-01-03'
    ])
)
display(df_dates)
new_df_dates = df_dates.shift(freq='MS',axis=0,periods=10)
display(new_df_dates)
print(f"\r{'='*50}")
display(df)
new_df = df.shift(axis=0,periods=1)
#Copy with values lagged by 1.
### (periods=1,freq=None,axis=0,fill_value=None,suffix=None)
## periods = 1 -> down, = -1 -> up.
## fill_value=0 -> might be problem for data type.
## freq='D'/'h'/'min'/'MS'

#print("df.shift(-1)")
display(new_df)

            sales
2026-01-01    100
2026-01-02    150
2026-01-03    200

            sales
2026-11-01    100
2026-11-01    150
2026-11-01    200

==================================================

    id      name   age  healthy  saving_count      country
0    1     ariel  25.0     True          1200       israel
1    2     nadav  24.0     True          1500       israel
2    3      maor  26.0    False          2140  north_korea
3    4      noam  26.0    False          1523     thailand
4    5      lior   NaN     True          3000         peru
5  106  hamarmir  45.0     True          2500       greece

    id   name   age healthy  saving_count      country
0  NaN   None   NaN     NaN           NaN         None
1  1.0  ariel  25.0    True        1200.0       israel
2  2.0  nadav  24.0    True        1500.0       israel
3  3.0   maor  26.0   False        2140.0  north_korea
4  4.0   noam  26.0   False        1523.0     thailand
5  5.0   lior   NaN    True        3000.0         peru

In [4]:
new_df = df['age'].cumsum()
#Cumulative sum.
### (axis=0,skipna=True)
## skipna=True -> Default, will skip the NaN Values, it will fill the NaN index with NaN value and continue normal.
# skipna=False -> will fill each of the next fields with NaN values.

print("df['age']\n",df['age'],'df["age"].cumsum()\n',new_df)

df['age']
 0    25.0
1    24.0
2    26.0
3    26.0
4     NaN
5    45.0
Name: age, dtype: float64 df["age"].cumsum()
 0     25.0
1     49.0
2     75.0
3    101.0
4      NaN
5    146.0
Name: age, dtype: float64

In [5]:
new_df = df['age'].cummax()
#Cumulative max.
### (axis=0,skipna=True)

print("df['age']\n",df['age'],"df['age'].cummax()\n",new_df)

df['age']
 0    25.0
1    24.0
2    26.0
3    26.0
4     NaN
5    45.0
Name: age, dtype: float64 df['age'].cummax()
 0    25.0
1    25.0
2    26.0
3    26.0
4     NaN
5    45.0
Name: age, dtype: float64

In [6]:
new_df = df['age'].cummin()
#Cumulative min.

print("df['age']\n",df['age'],"df['age'].cummin()\n",new_df)

df['age']
 0    25.0
1    24.0
2    26.0
3    26.0
4     NaN
5    45.0
Name: age, dtype: float64 df['age'].cummin()
 0    25.0
1    24.0
2    24.0
3    24.0
4     NaN
5    24.0
Name: age, dtype: float64

In [7]:
new_df = df['age'].cumprod()
#Cumulative product.
print("df['age']\n",df['age'],"df['age'].cumprod()\n",new_df)

df['age']
 0    25.0
1    24.0
2    26.0
3    26.0
4     NaN
5    45.0
Name: age, dtype: float64 df['age'].cumprod()
 0          25.0
1         600.0
2       15600.0
3      405600.0
4           NaN
5    18252000.0
Name: age, dtype: float64

In [8]:
new_df = df[['age','country']].rank(method='dense',numeric_only=True,pct=True)
#Ranks. Ties go to first value.
### (axis=0,method='average',numeric_only=False,na_option='keep',ascending=True,pct=False)
## method=['first','average','min','max','dense']
# method='first' -> first will get the higher rank.
# method = 'average' -> both same values will get their average rank.
# method = 'min' -> both same values will get the min value of both.
# method = 'max' -> both same values will get the max value of both.
# method = 'dense' -> both same values will get the same rank and next rank keep growing normally.
## na_option= ['keep','top','bottom']
## pct=True -> return the rank represented as percents.

print("df[['age','country']]\n",df[['age','country']],f"\n{'='*100}\ndf[['age','country']].rank(method='average',numeric_only=True,ascending=True)\n",new_df)

df[['age','country']]
     age      country
0  25.0       israel
1  24.0       israel
2  26.0  north_korea
3  26.0     thailand
4   NaN         peru
5  45.0       greece
====================================================================================================
df[['age','country']].rank(method='average',numeric_only=True,ascending=True)
     age
0  0.50
1  0.25
2  0.75
3  0.75
4   NaN
5  1.00

In [9]:
display(df)
new_df = df.groupby(by=['saving_count'],group_keys=True,dropna=False)['age'].max().reset_index()
#Return a GroupBy object, grouped by values, the next aggregate function will calculate the values in each group.
### (by,as_index=True,sort=True,group_keys=True,dropna=True)
## .reset_index() replacing the 'index keys' as regular columns.(normal df)
## by -> can act with lambda(index as input)/name_of_column/columns_array
# df[['age','saving_count']].groupby(by=lambda index: "Even" if index % 2 == 0 else "Odd",as_index=True)
#       index	saving_count
#       0	Even	3
#       1	Odd	    3
## as_index=True -> Default, declare the index column as the 'by' value.
## as_index=False -> creating new index column as reset.
## sort=True -> sorting the key values(indexes) not the field values.
## dropna=True -> as Default the Nan keys will be removed as any().
## group_keys=True -> Default, return the group keys as index.

display(new_df)

#mean = np.array([df.at[0,'saving_count'],df.at[2,'saving_count'],df.at[4,'saving_count']]).mean()
#print(mean)

    id      name   age  healthy  saving_count      country
0    1     ariel  25.0     True          1200       israel
1    2     nadav  24.0     True          1500       israel
2    3      maor  26.0    False          2140  north_korea
3    4      noam  26.0    False          1523     thailand
4    5      lior   NaN     True          3000         peru
5  106  hamarmir  45.0     True          2500       greece

   saving_count   age
0          1200  25.0
1          1500  24.0
2          1523  26.0
3          2140  26.0
4          2500  45.0
5          3000   NaN

In [11]:
def sum_example_function(series):
    return series.sum()

agg_df = df.agg({"age": ["mean","median","min", "max",'std'],
                 "saving_count": [lambda x: x.sum()],
                  "id": [sum_example_function]
                  })

#Aggregate group using function
# func = ["mean", "median", "min", "max", "std",lambda x: x.sum(),sum] --- input: df['saving_count'].

print(agg_df)

                            age  saving_count     id
mean                  29.200000           NaN    NaN
median                26.000000           NaN    NaN
min                   24.000000           NaN    NaN
max                   45.000000           NaN    NaN
std                    8.871302           NaN    NaN
<lambda>                    NaN       11863.0    NaN
sum_example_function        NaN           NaN  121.0