In [1]:
import pandas as pd
print("Imported")

Imported

In [55]:
dict_df = {
    "id"          : [1        ,2         ,3              ,4            ,5        ,106       ],
    "name"        : ["ariel"  ,"nadav"   ,"maor"         ,"noam"       ,"lior"   ,"hamarmir"],
    "age"         : [25       , 24       ,21             ,26           ,32     ,45        ],
    "healthy"     : [True     ,True      ,False          ,False        ,True     ,True      ],
    "saving_count": [1200     ,1500      ,2140           ,1523         ,3000     ,2500      ],
    "addicted"    : ["high"   ,"medium"  ,"high"         ,"medium"     ,"less"   ,"not"],
    "country"     : ["israel" ,"israel"  ,'north_korea'  ,"thailand"   ,'peru'   ,'greece'  ]
}

df = pd.DataFrame(dict_df,
                  columns=list(dict_df.keys()),
                  index=pd.to_datetime(["2026-10-01", "2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-6"]))

display(df)

             id      name  age  healthy  saving_count addicted      country
2026-10-01    1     ariel   25     True          1200     high       israel
2026-10-02    2     nadav   24     True          1500   medium       israel
2026-10-03    3      maor   21    False          2140     high  north_korea
2026-10-04    4      noam   26    False          1523   medium     thailand
2026-10-05    5      lior   32     True          3000     less         peru
2026-10-06  106  hamarmir   45     True          2500      not       greece

In [9]:
display(df[['age']].reset_index(drop=True))
age_df = df[['age']].expanding(
    min_periods=2
).mean().reset_index(drop=True)
#Return an Expanding object allowing summary functions to be applied cumulatively.
### (min_periods=1,method="single")
## min_periods=1 -> declare the min_periods-values to start the cumulatively aggregate function,
# until the min_periods value it will consider as NaN.
## method = 'single' -> each column by its self.
## method = 'table' -> all the table will be calculated in condition the agg function supports.


display(age_df)

    age
0  25.0
1  24.0
2  26.0
3  26.0
4   NaN
5  45.0

     age
0    NaN
1  24.50
2  25.00
3  25.25
4  25.25
5  29.20

In [65]:
display(df)
age_df = df[['age']].rolling(
    window='2D',center=False
).mean()
#Return a Rolling object allowing summary functions to be applied to windows of length n.
###(window,min_periods=None,center=False,win_type=None,on=None,axis=0,closed=None,step=None,method="single")
## window=2 -> each cell will calculate the agg on the previous window_value cells,
# that is why the first (window_value-1) rows will be NaN.
## window='3D',on='date'(type: pd.to_datetime. as 'on') -> will calculate the previous '3D'(3 days).
## center=True -> will calculate forward cells. center=False -> will calculate only previous cells.
## step=2 -> it will calculate with jump of 2 cells between the cells.



display(age_df)

             id      name  age  healthy  saving_count addicted      country
2026-10-01    1     ariel   25     True          1200     high       israel
2026-10-02    2     nadav   24     True          1500   medium       israel
2026-10-03    3      maor   21    False          2140     high  north_korea
2026-10-04    4      noam   26    False          1523   medium     thailand
2026-10-05    5      lior   32     True          3000     less         peru
2026-10-06  106  hamarmir   45     True          2500      not       greece

             age
2026-10-01  25.0
2026-10-02  24.5
2026-10-03  22.5
2026-10-04  23.5
2026-10-05  29.0
2026-10-06  38.5